apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zbms.ibm.com
spec:
  group: ibm.com
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
  scope: Namespaced 
  names:
    plural: zbms
    singular: zbm
    kind: Zbm
    shortNames:
    - z
